# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MV' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MV
      pod 'JTAppleCalendar', '~> 7.0'


  target 'MVTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MVUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
